
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    parameters:
      python_version:
        type: string
    docker:
      - image: circleci/python:<<parameters.python_version>>
      - image: redislabs/rebloom:edge

    working_directory: ~/repo

    steps:
      - checkout

#      - restore_cache: # Download and cache dependencies
#          keys:
#          - v1-dependencies-{{ checksum "pyproject.toml" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
#
      - run:
          name: install tox dependencies
          command: |
            pip install --user -r requirements.txt

#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "pyproject.toml" }}

      - run:
          name: build sdist
          command: poetry build --format sdist

      - run:
          name: build wheel
          command: poetry build --format wheel

      - run:
          name: run tests
          command: |
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports

  build_nightly:
    docker:
      - image: circleci/python:3.7.1
      - image: redislabs/rebloom:edge

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: # Download and cache dependencies
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            REDIS_PORT=6379 python test_commands.py

on-any-branch: &on-any-branch
  filters:
    branches:
      only:
        - /.*/
    tags:
      ignore: /.*/

workflows:
  version: 2
  ci:
    jobs:
      - build:
          <<: *on-any-branch
          matrix:
            parameters:
              python_version:
                - "3.6.9"
                - "3.7.9"
                - "3.8.9"
                - "3.9.4"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly
